@startuml
class map.level5 {
- {static} char[][] mapPattern
+ {static} char[][] getMapPattern()
+ {static} void setMapPattern(char[][])
}
class object.Bullet {
- int x
- int y
- Direction direction
+ <<Create>> Bullet(int,int,Direction)
+ void move(int)
+ int getX()
+ int getY()
+ Direction getDirection()
+ void setX(int)
+ void setY(int)
+ void setDirection(Direction)
}
class logic.GhostSpawner {
- {static} ArrayList<Pair<Integer,Integer>> spawnablePosition
- {static} ArrayList<Ghost> ghosts
+ <<Create>> GhostSpawner()
+ {static} void spawnGhost()
+ {static} void updateSpawnablePosition()
+ {static} ArrayList<Ghost> spawnerSpawnGhost(ArrayList<Pair<Integer,Integer>>,ArrayList<Ghost>)
- {static} boolean isOnFootpath(int,int)
- {static} boolean isWithinRangeOfPlayer(int,int)
+ {static} ArrayList<Ghost> getGhosts()
+ {static} void setGhosts(ArrayList<Ghost>)
}
class logic.ImageManager {
- {static} int blockSize
- Image characterUp
- Image characterDown
- Image characterLeft
- Image characterRight
- Image currentCharacterImage
- Image wall
- Image footPath
- Image whiteDot
- Image bulletRight
- Image bulletUp
- Image bulletLeft
- Image bulletDown
- Image redGhost
+ <<Create>> ImageManager()
+ Image getCurrentCharacterImage()
+ void setCurrentCharacterImage(Image)
+ Image getCharacterUp()
+ void setCharacterUp(Image)
+ Image getCharacterDown()
+ void setCharacterDown(Image)
+ Image getCharacterLeft()
+ void setCharacterLeft(Image)
+ Image getCharacterRight()
+ void setCharacterRight(Image)
+ Image getWall()
+ void setWall(Image)
+ Image getFootPath()
+ void setFootPath(Image)
+ Image getWhiteDot()
+ void setWhiteDot(Image)
+ Image getBulletRight()
+ void setBulletRight(Image)
+ Image getBulletUp()
+ void setBulletUp(Image)
+ Image getBulletLeft()
+ void setBulletLeft(Image)
+ Image getBulletDown()
+ void setBulletDown(Image)
+ Image getRedGhost()
+ void setRedGhost(Image)
}
class logic.KeyHandler {
- PlayerMovement playerMovement
- BulletLogic bulletLogic
- Runnable updateMap
- Runnable updateSpawnablePosition
- int blockSize
- int currentLevel
+ <<Create>> KeyHandler(PlayerMovement,BulletLogic,Runnable,Runnable,int,int)
+ void handle(KeyEvent)
}
class component.SupermarketFont {
+ <<Create>> SupermarketFont(String,Integer,Paint)
+ <<Create>> SupermarketFont(String,Integer)
+ <<Create>> SupermarketFont(String)
}
class main.Player {
- int playerX
- int playerY
+ int getPlayerX()
+ void setPlayerX(int)
+ int getPlayerY()
+ void setPlayerY(int)
}
class map.level2 {
- {static} char[][] mapPattern
+ {static} char[][] getMapPattern()
+ {static} void setMapPattern(char[][])
}
class component.BBFont {
+ <<Create>> BBFont(String,Integer,Paint)
+ <<Create>> BBFont(String,Integer)
+ <<Create>> BBFont(String)
}
class map.level3 {
- {static} char[][] mapPattern
+ {static} char[][] getMapPattern()
+ {static} void setMapPattern(char[][])
}
class component.TekoFont {
+ <<Create>> TekoFont(String,Integer,Paint)
+ <<Create>> TekoFont(String,Integer)
+ <<Create>> TekoFont(String)
}
class main.Main {
+ void start(Stage)
+ {static} void main(String[])
}
class main.GamePanel {
- Label pointLabel
- Label levelLabel
- {static} GamePanel instance
- PlayerMovement playerMovement
- BulletLogic bulletLogic
- MapLoader mapLoader
- GhostSpawner ghostSpawner
- ImageManager imageManager
- int screenWidth
- int screenHeight
- int playerX
- int playerY
- int blockSize
- int screenWidthBlocks
- int screenHeightBlocks
- char[][] mapPattern
- ArrayList<Bullet> bullets
- {static} ArrayList<Ghost> ghosts
- Direction playerDirection
- {static} ArrayList<Pair<Integer,Integer>> spawnablePosition
~ Media buzzer
~ MediaPlayer gunshotSound
- boolean hasGameEnded
- boolean isUpdatingMap
- int currentPoint
- int currentLevel
- int[] extraGhost
- long startTimeNano
+ <<Create>> GamePanel()
+ int getScreenWidth()
+ void setScreenWidth(int)
+ int getScreenHeight()
+ void setScreenHeight(int)
+ int getPlayerX()
+ void setPlayerX(int)
+ int getPlayerY()
+ void setPlayerY(int)
+ int getBlockSize()
+ int getScreenWidthBlocks()
+ int getScreenHeightBlocks()
+ char[][] getMapPattern()
+ void setMapPattern(char[][])
+ ArrayList<Bullet> getBullets()
+ void setBullets(ArrayList<Bullet>)
+ {static} ArrayList<Ghost> getGhosts()
+ {static} void setGhosts(ArrayList<Ghost>)
+ Direction getPlayerDirection()
+ void setPlayerDirection(Direction)
+ {static} ArrayList<Pair<Integer,Integer>> getSpawnablePosition()
+ {static} void setSpawnablePosition(ArrayList<Pair<Integer,Integer>>)
+ Media getBuzzer()
+ void setBuzzer(Media)
+ boolean isHasGameEnded()
+ void setHasGameEnded(boolean)
+ boolean isUpdatingMap()
+ void setUpdatingMap(boolean)
+ int getCurrentPoint()
+ void setCurrentPoint(int)
+ int getCurrentLevel()
+ void setCurrentLevel(int)
+ MediaPlayer getGunshotSound()
+ void setGunshotSound(MediaPlayer)
+ {static} GamePanel getInstance()
+ {static} void setInstance(GamePanel)
+ PlayerMovement getPlayerMovement()
+ BulletLogic getBulletLogic()
+ MapLoader getMapLoader()
+ GhostSpawner getGhostSpawner()
+ ImageManager getImageManager()
}
class map.levelMap {
- {static} char[][] mapPattern
- {static} ArrayList<Pair<Integer,Integer>> pos
- {static} ArrayList<Pair<Integer,Integer>> updateEmptyPosition()
- {static} ArrayList<Pair<Integer,Integer>> getCurrentPosition()
+ {static} char[][] getMapPattern()
+ {static} void setMapPattern(char[][])
+ {static} ArrayList<Pair<Integer,Integer>> getPos()
+ {static} void setPos(ArrayList<Pair<Integer,Integer>>)
}
class logic.PlayerMovement {
- int blockSize
- Image characterUp
- Image characterDown
- Image characterLeft
- Image characterRight
- Image wall
- Image footPath
~ Image whiteDot
~ Image bulletRight
~ Image bulletUp
~ Image bulletLeft
~ Image bulletDown
~ Image redGhost
+ void movePlayer(int,int)
+ void repaint()
+ void moveGhosts()
- void updateDirection(int,int)
}
class ghost.Ghost {
- int x
- int y
- int speed
- Direction ghostDirection
+ <<Create>> Ghost()
+ <<Create>> Ghost(Direction)
+ <<Create>> Ghost(int,int)
+ <<Create>> Ghost(int,int,int)
+ <<Create>> Ghost(int,int,int,Direction)
+ void move(char[][])
- boolean isValidMove(int,int,char[][])
- void changeDirection()
+ int getX()
+ void setX(int)
+ int getY()
+ void setY(int)
+ int getSpeed()
+ void setSpeed(int)
+ Direction getGhostDirection()
+ void setGhostDirection(Direction)
}
class logic.GameInstance {
+ <<Create>> GameInstance()
+ void resetGameInstance()
}
class logic.BulletLogic {
+ <<Create>> BulletLogic()
+ void updateBullets()
- boolean bulletHitsWall(int,int)
+ void shootBullet()
+ void updateBulletGhostCollisions()
}
class ghost.SpeedyGhost {
+ <<Create>> SpeedyGhost()
+ <<Create>> SpeedyGhost(int,int)
+ <<Create>> SpeedyGhost(int,int,int)
}
class component.RetroFont {
+ <<Create>> RetroFont(String,Integer,Paint)
+ <<Create>> RetroFont(String,Integer)
+ <<Create>> RetroFont(String)
}
enum object.Direction {
+  UP
+  DOWN
+  LEFT
+  RIGHT
}
class scene.HomeScreen {
- Stage stage
- {static} Scene scene
- {static} StackPane root
- VBox buttonContainer
- SupermarketFont title
- BBFont title2
- GameButton playButton
- GameButton tutorialButton
- GameButton creditButton
- GameButton quitButton
- boolean fullScreen
- Color buttonColor
+ <<Create>> HomeScreen(Stage)
- void componentSetup(GameInstance)
- void eventSetup(GameInstance)
- void stageSetup()
+ {static} StackPane getRoot()
+ {static} Scene getScene()
}
class map.level4 {
- {static} char[][] mapPattern
+ {static} char[][] getMapPattern()
+ {static} void setMapPattern(char[][])
}
class map.level1 {
- {static} char[][] mapPattern
+ {static} char[][] getMapPattern()
+ {static} void setMapPattern(char[][])
}
class logic.MapLoader {
~ {static} boolean isUpdatingMap
+ {static} GamePanel updateMap(int)
+ {static} boolean isIsUpdatingMap()
+ {static} void setIsUpdatingMap(boolean)
}
class scene.LoadingScreen {
- ImageView imageView
+ void initialize(URL,ResourceBundle)
}
class component.GameButton {
- Rectangle background
+ <<Create>> GameButton(int,int,int,Paint)
+ <<Create>> GameButton()
+ void addText(String,int,Paint)
+ void setColor(Paint)
}


map.levelMap <|-- map.level5
javafx.event.EventHandler <|.. logic.KeyHandler
javafx.scene.text.Text <|-- component.SupermarketFont
map.levelMap <|-- map.level2
javafx.scene.text.Text <|-- component.BBFont
map.levelMap <|-- map.level3
javafx.scene.text.Text <|-- component.TekoFont
javafx.application.Application <|-- main.Main
javafx.scene.layout.Pane <|-- main.GamePanel
ghost.Ghost <|-- ghost.SpeedyGhost
javafx.scene.text.Text <|-- component.RetroFont
map.levelMap <|-- map.level4
map.levelMap <|-- map.level1
javafx.fxml.Initializable <|.. scene.LoadingScreen
javafx.scene.layout.StackPane <|-- component.GameButton
@enduml